[package]
name = "bs_site_builder"
version = "0.1.2"
edition = "2024"

[[bin]]
name = "bs"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
chrono = "0.4.41"
clearscreen = "4.0.1"
dialoguer = "0.11.0"
itertools = "0.14.0"
minijinja = { version = "2.10.2", features = ["builtins", "custom_syntax", "debug", "json", "loader", "urlencode"] }
permissions = "0.5.1"
port_check = "0.2.1"
rust-embed = "8.7.2"
serde_json = "1.0.140"
serde_json5 = "0.2.1"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
tower-http = { version= "0.6.6", features = ["fs"] }
tower-livereload = "0.9.6"
walkdir = "2.5.0"
watchexec = "8.0.1"
watchexec-events = "6.0.0"
watchexec-signals = "5.0.0"
