[package]
name = "ssbuild"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
chrono = "0.4.41"
clearscreen = "4.0.1"
itertools = "0.14.0"
minijinja = { version = "2.10.2", features = ["custom_syntax", "loader"] }
permissions = "0.5.1"
port_check = "0.2.1"
rust-embed = "8.7.2"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
tower-http = { version= "0.6.6", features = ["fs"] }
tower-livereload = "0.9.6"
walkdir = "2.5.0"
watchexec = "8.0.1"
watchexec-events = "6.0.0"
watchexec-signals = "5.0.0"
